---
title: "R Notebook"
output: html_notebook
---
https://www.usna.edu/Users/oceano/pguth/md_help/html/tbme6h0z.htm
```{r setup}
library(sf)
library(stars)
library(xml2)
library(flatxml)
library(tidyverse)
```

```{r}
dir.create("kml")
zipF<- "baronskogenelg.kmz"
outDir<-"kml/"
unzip(zipF,exdir=outDir)
```


```{r}
doc.kml <- read_xml("kml/doc.kml")

jpg <- xml_text(xml_find_all(doc.kml, ".//d1:href", xml_ns(doc.kml)))
north <- xml_text(xml_find_all(doc.kml, ".//d1:north", xml_ns(doc.kml)))
south <- xml_text(xml_find_all(doc.kml, ".//d1:south", xml_ns(doc.kml)))
east <- xml_text(xml_find_all(doc.kml, ".//d1:east", xml_ns(doc.kml)))
west <- xml_text(xml_find_all(doc.kml, ".//d1:west", xml_ns(doc.kml)))
rotation <- xml_text(xml_find_all(doc.kml, ".//d1:rotation", xml_ns(doc.kml)))
file_name <- substr(jpg, 7, 24)
df <- data.frame(jpg,north,south,east,west,rotation,file_name)           
```
For a description of the world file look at the following sites:
https://en.wikipedia.org/wiki/World_file
https://egb13.net/worldfile-calculator
#Loop
This section loops through all the raster files and extract height and width from the images files. The coordinates are extracted from the KML file.
```{r}

file_list <- list.files("kml", pattern = "*.jpg", recursive = T, full.names = T)
for (file in file_list) {
  tmp <- raster::raster(file)
  file_name_out <- substr(file, 11, 28)
  tmp1 <- df %>% dplyr::filter(file_name_out == file_name)
  #df[df$file_name_out == file_name]
  south <- as.numeric(as.character(tmp1$south[1])) 
  print(south)
  north <- as.numeric(as.character(tmp1$north[1]))
  print(north)
  east <- as.numeric(as.character(tmp1$east[1]))
  print(east)
  west <- as.numeric(as.character(tmp1$west[1]))
  print(west)
  rotation <- as.numeric(as.character(tmp1$rotation[1]))
  height = dim(tmp)[2]
  print(height)
  width = dim(tmp)[1]
  print(width)
  if (south < east) {
    t = +south
    south = east
    east = t
  }

  if (east > west) {
    t = +west
    east = west
    west = t
  }
# dimX=$(echo "($east-($west))/$width" | bc -l)
# dimY=$(echo "($south-($north))/$height" | bc -l)
  ppx = (east - west) / xsize
  ppy = (south - north) / ysize
print(ppx)
print(ppy)
  cat(
    ppx,
    "0",
    "0", #rotation,
    ppy,
    lat2 = lat2 + (ppx / 2), # // y center of pixel
    lon2 = lon2 + (ppy / 2), # // x center of pixel
    file = paste0("kml/files/", file_name_out, ".jgw"),
    sep = "\n",
    append = F
  )
}
# C=$(echo "$west+($dimX/2)" | bc -l)
# F=$(echo "$north+($dimY/2)" | bc -l)
```


